101

diff --git a/python-hello_world/101-compile b/python-hello_world/101-compile
--- a/python-hello_world/101-compile
+++ b/python-hello_world/101-compile
@@ -1,20 +1,17 @@
 #!/bin/bash
 if [ -z "$PYFILE" ]; then
-  echo "Error: Environment variable \$PYFILE is not set."
-  exit 1
-fi
-
-if [ ! -f "$PYFILE" ]; then
-  echo "Error: The specified Python file '$PYFILE' does not exist."
-  exit 1
+    echo "Error: Environment variable PYFILE is not set."
+    exit 1
 fi
 
 # Compile the Python script
+py_compile_file="$PYFILE"c
 python3 -m py_compile "$PYFILE"
-
-if [ $? -eq 0 ]; then
-  echo "Compiling $PYFILE ..."
+if [ -f "$py_compile_file" ]; then
+    echo "Compiling $PYFILE ..."
+    mv "$py_compile_file" .
+    exit 0
 else
-  echo "Error: Failed to compile $PYFILE."
-  exit 1
+    echo "Error: Failed to compile $PYFILE."
+    exit 1
 fi
